version: "3.8"

services:
  symptom_app:
    build: .
    container_name: symptom_recommender
    ports:
      - "8000:8000"   # FastAPI
      - "8501:8501"   # Streamlit
    volumes:
      - .:/app        # mount code from the current folder into the container
    command: >
      bash -c "
        uvicorn api.app:app --reload --host 0.0.0.0 --port 8000 &
        streamlit run ui.py --server.port 8501 --server.address 0.0.0.0
      "